specfile_path: tools/packaging/rpm/systemd.spec
synced_files:
  - .packit.yaml
  - src: tools/packaging/rpm/systemd.spec
    dest: systemd.spec
upstream_package_name: systemd
downstream_package_name: systemd
#upstream_ref: v245

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-rawhide-x86_64

      #- job: tests
      #  trigger: pull_request
      #  metadata:
      #    targets:
      #    - fedora-rawhide-x86_64
