---
# vi: ts=2 sw=2 et:
# SPDX-License-Identifier: LGPL-2.1-or-later
#
name: Unit tests
on:
  pull_request:
    branches:
      - main
      - v[0-9]+-stable

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.run_phase }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        run_phase: [CLANG_ASAN_UBSAN]
    steps:
      - name: Repository checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: Install build dependencies
        run: sudo -E .github/workflows/unit_tests.sh SETUP

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Build & test (${{ matrix.run_phase }})
        run: sudo -E .github/workflows/unit_tests.sh RUN_${{ matrix.run_phase }}
